# Generated by Django 4.2.4 on 2023-10-27 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("AppRapida", "0006_remove_doc_axe_remove_doc_envoi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Axe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("isactive", models.IntegerField(default=1)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "bureau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRapida.bureaux",
                    ),
                ),
            ],
            options={
                "db_table": "axe",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Envoi",
            fields=[
                (
                    "num_envoi",
                    models.CharField(
                        db_column="num_envoi",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "poids",
                    models.DecimalField(
                        blank=True,
                        db_column="poids",
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("bureau_exp", models.CharField(db_column="bureau_exp", max_length=50)),
                (
                    "bureau_dest",
                    models.CharField(db_column="bureau_dest", max_length=50),
                ),
                ("type_envoi", models.CharField(db_column="type_envoi", max_length=50)),
                ("dateEnvoi", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "envoi",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(db_column="nom", max_length=50)),
                ("prenom", models.CharField(db_column="prenom", max_length=50)),
                ("tel", models.CharField(db_column="tel", max_length=50)),
                ("adresse", models.CharField(db_column="adresse", max_length=50)),
                ("mail", models.CharField(db_column="mail", max_length=50)),
                ("numeroId", models.CharField(db_column="numeroId", max_length=50)),
                ("categorie", models.CharField(db_column="categorie", max_length=50)),
            ],
            options={
                "db_table": "personne",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Historique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statut", models.CharField(max_length=10)),
                ("isactive", models.IntegerField(default=1)),
                ("date_historique", models.DateTimeField(auto_now_add=True)),
                (
                    "bureau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRapida.bureaux",
                    ),
                ),
                (
                    "envoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appRapidaCorps.envoi",
                    ),
                ),
            ],
            options={
                "db_table": "historique",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_facture",
                    models.CharField(db_column="numero_facture", max_length=50),
                ),
                (
                    "numero_bordereau",
                    models.CharField(db_column="numero_bordereau", max_length=50),
                ),
                (
                    "prix_rapida",
                    models.CharField(db_column="prix_rapida", max_length=50),
                ),
                (
                    "type_paiement",
                    models.CharField(db_column="type_paiement", max_length=50),
                ),
                ("date_facture", models.DateTimeField(auto_now_add=True)),
                (
                    "bureau",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppRapida.bureaux",
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinataire",
                        to="appRapidaCorps.personne",
                    ),
                ),
                (
                    "envoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appRapidaCorps.envoi",
                    ),
                ),
                (
                    "expediteur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expediteur",
                        to="appRapidaCorps.personne",
                    ),
                ),
            ],
            options={
                "db_table": "facture",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("convoyeur", models.CharField(max_length=50)),
                ("voiture", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "axe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appRapidaCorps.axe",
                    ),
                ),
                (
                    "envoi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appRapidaCorps.envoi",
                    ),
                ),
            ],
            options={
                "db_table": "docs",
                "managed": True,
            },
        ),
    ]
