# Generated by Django 4.2.4 on 2023-10-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppRapida", "0007_remove_bureaux_id_alter_bureaux_codique"),
        ("appRapidaCorps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeEnvoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "rapida_typeenvoi",
                "managed": True,
            },
        ),
        migrations.RemoveField(
            model_name="axe",
            name="bureau",
        ),
        migrations.AlterField(
            model_name="envoi",
            name="bureau_dest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bureau_dest",
                to="AppRapida.bureaux",
            ),
        ),
        migrations.AlterField(
            model_name="envoi",
            name="bureau_exp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bureau_exp",
                to="AppRapida.bureaux",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="numero_bordereau",
            field=models.CharField(
                blank=True, db_column="numero_bordereau", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="numero_facture",
            field=models.CharField(
                blank=True, db_column="numero_facture", max_length=50, null=True
            ),
        ),
        migrations.AlterModelTable(
            name="axe",
            table="rapida_axe",
        ),
        migrations.AlterModelTable(
            name="doc",
            table="rapida_docs",
        ),
        migrations.AlterModelTable(
            name="envoi",
            table="rapida_envoi",
        ),
        migrations.AlterModelTable(
            name="facture",
            table="rapida_facture",
        ),
        migrations.AlterModelTable(
            name="historique",
            table="rapida_historique",
        ),
        migrations.AlterModelTable(
            name="personne",
            table="rapida_personne",
        ),
        migrations.AddField(
            model_name="axe",
            name="bureau",
            field=models.ManyToManyField(
                related_name="axe_bureau", to="AppRapida.bureaux"
            ),
        ),
        migrations.AlterField(
            model_name="envoi",
            name="type_envoi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_envoi",
                to="appRapidaCorps.typeenvoi",
            ),
        ),
    ]
