# Generated by Django 4.2.4 on 2023-10-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appRapidaCorps",
            "0002_typeenvoi_remove_axe_bureau_alter_envoi_bureau_dest_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="personne",
            name="categorie",
            field=models.IntegerField(db_column="categorie", default=0),
        ),
    ]
