# Generated by Django 4.2.4 on 2023-10-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appRapidaCorps", "0003_alter_personne_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="type_paiement",
            field=models.IntegerField(
                choices=[(0, "Depot"), (1, "Collect")],
                db_column="type_paiement",
                max_length=50,
            ),
        ),
    ]
