# Generated by Django 4.2.4 on 2023-11-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppRapida", "0007_remove_bureaux_id_alter_bureaux_codique"),
        ("appRapidaCorps", "0006_alter_facture_type_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="bureau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppRapida.bureaux"
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="expediteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expediteur",
                to="appRapidaCorps.personne",
            ),
        ),
    ]
