# Generated by Django 4.2.4 on 2023-11-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appRapidaCorps", "0009_alter_facture_type_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envoi",
            name="poids",
            field=models.DecimalField(
                blank=True, db_column="poids", decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="envoi",
            name="type_envoi",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="TypeEnvoi",
        ),
    ]
