# Generated by Django 4.2.4 on 2023-12-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appRapidaCorps", "0010_alter_envoi_poids_alter_envoi_type_envoi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="statut",
            field=models.IntegerField(default=1),
        ),
    ]
