# Generated by Django 4.2.4 on 2023-12-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appRapidaCorps", "0011_facture_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="doc",
            name="owner",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
