# Generated by Django 4.2.4 on 2023-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppRapida", "0002_alter_tarif_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bureaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codique", models.IntegerField()),
                ("province", models.IntegerField(blank=True, null=True)),
                ("codeclasse", models.IntegerField(blank=True, null=True)),
                ("nombureau", models.CharField(blank=True, max_length=50, null=True)),
                ("classe", models.CharField(blank=True, max_length=50, null=True)),
                ("ccp", models.CharField(blank=True, max_length=10, null=True)),
                ("sigle", models.CharField(blank=True, max_length=5, null=True)),
                ("nompublic", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "bureaux",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Zonify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depart", models.CharField(max_length=50)),
                ("ncodiquebur1", models.IntegerField()),
                ("arrive", models.CharField(max_length=50)),
                ("ncodiquebur2", models.IntegerField()),
                ("longueur", models.FloatField()),
                ("zone", models.IntegerField()),
                ("zonemodifier", models.IntegerField()),
            ],
            options={
                "db_table": "zonify",
                "managed": True,
            },
        ),
    ]
