# Generated by Django 4.2.4 on 2023-10-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppRapida", "0005_alter_bureaux_options_alter_tarif_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doc",
            name="axe",
        ),
        migrations.RemoveField(
            model_name="doc",
            name="envoi",
        ),
        migrations.RemoveField(
            model_name="facture",
            name="bureau",
        ),
        migrations.RemoveField(
            model_name="facture",
            name="destinataire",
        ),
        migrations.RemoveField(
            model_name="facture",
            name="envoi",
        ),
        migrations.RemoveField(
            model_name="facture",
            name="expediteur",
        ),
        migrations.RemoveField(
            model_name="historique",
            name="bureau",
        ),
        migrations.RemoveField(
            model_name="historique",
            name="envoi",
        ),
        migrations.AlterModelOptions(
            name="bureaux",
            options={},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tarif",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AlterModelOptions(
            name="zonify",
            options={},
        ),
        migrations.AlterModelTable(
            name="bureaux",
            table=None,
        ),
        migrations.AlterModelTable(
            name="company",
            table=None,
        ),
        migrations.AlterModelTable(
            name="tarif",
            table=None,
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="zonify",
            table=None,
        ),
        migrations.DeleteModel(
            name="Axe",
        ),
        migrations.DeleteModel(
            name="Doc",
        ),
        migrations.DeleteModel(
            name="Envoi",
        ),
        migrations.DeleteModel(
            name="Facture",
        ),
        migrations.DeleteModel(
            name="Historique",
        ),
        migrations.DeleteModel(
            name="Personne",
        ),
    ]
