# Generated by Django 4.2.4 on 2023-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppRapida", "0006_remove_doc_axe_remove_doc_envoi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bureaux",
            name="id",
        ),
        migrations.AlterField(
            model_name="bureaux",
            name="codique",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
